/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppAuthenticatedImport } from './routes/_app/_authenticated'
import { Route as AppAuthenticatedSitesLayoutImport } from './routes/_app/_authenticated/sites/_layout'
import { Route as AppAuthenticatedOnboardingLayoutImport } from './routes/_app/_authenticated/onboarding/_layout'
import { Route as AppAuthenticatedSitesLayoutIndexImport } from './routes/_app/_authenticated/sites/_layout.index'
import { Route as AppAuthenticatedSitesSiteIdIndexImport } from './routes/_app/_authenticated/sites/$siteId/index'
import { Route as AppAuthenticatedSitesLayoutSettingsImport } from './routes/_app/_authenticated/sites/_layout.settings'
import { Route as AppAuthenticatedOnboardingLayoutUsernameImport } from './routes/_app/_authenticated/onboarding/_layout.username'
import { Route as AppAuthenticatedSitesLayoutSettingsIndexImport } from './routes/_app/_authenticated/sites/_layout.settings.index'

// Create Virtual Routes

const AppAuthenticatedSitesImport = createFileRoute(
  '/_app/_authenticated/sites',
)()
const AppAuthenticatedOnboardingImport = createFileRoute(
  '/_app/_authenticated/onboarding',
)()

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppAuthenticatedRoute = AppAuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthenticatedSitesRoute = AppAuthenticatedSitesImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)

const AppAuthenticatedOnboardingRoute = AppAuthenticatedOnboardingImport.update(
  {
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any,
)

const AppAuthenticatedSitesLayoutRoute =
  AppAuthenticatedSitesLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AppAuthenticatedSitesRoute,
  } as any)

const AppAuthenticatedOnboardingLayoutRoute =
  AppAuthenticatedOnboardingLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AppAuthenticatedOnboardingRoute,
  } as any)

const AppAuthenticatedSitesLayoutIndexRoute =
  AppAuthenticatedSitesLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthenticatedSitesLayoutRoute,
  } as any)

const AppAuthenticatedSitesSiteIdIndexRoute =
  AppAuthenticatedSitesSiteIdIndexImport.update({
    id: '/$siteId/',
    path: '/$siteId/',
    getParentRoute: () => AppAuthenticatedSitesRoute,
  } as any)

const AppAuthenticatedSitesLayoutSettingsRoute =
  AppAuthenticatedSitesLayoutSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthenticatedSitesLayoutRoute,
  } as any)

const AppAuthenticatedOnboardingLayoutUsernameRoute =
  AppAuthenticatedOnboardingLayoutUsernameImport.update({
    id: '/username',
    path: '/username',
    getParentRoute: () => AppAuthenticatedOnboardingLayoutRoute,
  } as any)

const AppAuthenticatedSitesLayoutSettingsIndexRoute =
  AppAuthenticatedSitesLayoutSettingsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthenticatedSitesLayoutSettingsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/_authenticated': {
      id: '/_app/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthenticatedImport
      parentRoute: typeof AppImport
    }
    '/_app/_authenticated/onboarding': {
      id: '/_app/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthenticatedOnboardingImport
      parentRoute: typeof AppAuthenticatedImport
    }
    '/_app/_authenticated/onboarding/_layout': {
      id: '/_app/_authenticated/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthenticatedOnboardingLayoutImport
      parentRoute: typeof AppAuthenticatedOnboardingRoute
    }
    '/_app/_authenticated/sites': {
      id: '/_app/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AppAuthenticatedSitesImport
      parentRoute: typeof AppAuthenticatedImport
    }
    '/_app/_authenticated/sites/_layout': {
      id: '/_app/_authenticated/sites/_layout'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AppAuthenticatedSitesLayoutImport
      parentRoute: typeof AppAuthenticatedSitesRoute
    }
    '/_app/_authenticated/onboarding/_layout/username': {
      id: '/_app/_authenticated/onboarding/_layout/username'
      path: '/username'
      fullPath: '/onboarding/username'
      preLoaderRoute: typeof AppAuthenticatedOnboardingLayoutUsernameImport
      parentRoute: typeof AppAuthenticatedOnboardingLayoutImport
    }
    '/_app/_authenticated/sites/_layout/settings': {
      id: '/_app/_authenticated/sites/_layout/settings'
      path: '/settings'
      fullPath: '/sites/settings'
      preLoaderRoute: typeof AppAuthenticatedSitesLayoutSettingsImport
      parentRoute: typeof AppAuthenticatedSitesLayoutImport
    }
    '/_app/_authenticated/sites/$siteId/': {
      id: '/_app/_authenticated/sites/$siteId/'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof AppAuthenticatedSitesSiteIdIndexImport
      parentRoute: typeof AppAuthenticatedSitesImport
    }
    '/_app/_authenticated/sites/_layout/': {
      id: '/_app/_authenticated/sites/_layout/'
      path: '/'
      fullPath: '/sites/'
      preLoaderRoute: typeof AppAuthenticatedSitesLayoutIndexImport
      parentRoute: typeof AppAuthenticatedSitesLayoutImport
    }
    '/_app/_authenticated/sites/_layout/settings/': {
      id: '/_app/_authenticated/sites/_layout/settings/'
      path: '/'
      fullPath: '/sites/settings/'
      preLoaderRoute: typeof AppAuthenticatedSitesLayoutSettingsIndexImport
      parentRoute: typeof AppAuthenticatedSitesLayoutSettingsImport
    }
  }
}

// Create and export the route tree

interface AppAuthenticatedOnboardingLayoutRouteChildren {
  AppAuthenticatedOnboardingLayoutUsernameRoute: typeof AppAuthenticatedOnboardingLayoutUsernameRoute
}

const AppAuthenticatedOnboardingLayoutRouteChildren: AppAuthenticatedOnboardingLayoutRouteChildren =
  {
    AppAuthenticatedOnboardingLayoutUsernameRoute:
      AppAuthenticatedOnboardingLayoutUsernameRoute,
  }

const AppAuthenticatedOnboardingLayoutRouteWithChildren =
  AppAuthenticatedOnboardingLayoutRoute._addFileChildren(
    AppAuthenticatedOnboardingLayoutRouteChildren,
  )

interface AppAuthenticatedOnboardingRouteChildren {
  AppAuthenticatedOnboardingLayoutRoute: typeof AppAuthenticatedOnboardingLayoutRouteWithChildren
}

const AppAuthenticatedOnboardingRouteChildren: AppAuthenticatedOnboardingRouteChildren =
  {
    AppAuthenticatedOnboardingLayoutRoute:
      AppAuthenticatedOnboardingLayoutRouteWithChildren,
  }

const AppAuthenticatedOnboardingRouteWithChildren =
  AppAuthenticatedOnboardingRoute._addFileChildren(
    AppAuthenticatedOnboardingRouteChildren,
  )

interface AppAuthenticatedSitesLayoutSettingsRouteChildren {
  AppAuthenticatedSitesLayoutSettingsIndexRoute: typeof AppAuthenticatedSitesLayoutSettingsIndexRoute
}

const AppAuthenticatedSitesLayoutSettingsRouteChildren: AppAuthenticatedSitesLayoutSettingsRouteChildren =
  {
    AppAuthenticatedSitesLayoutSettingsIndexRoute:
      AppAuthenticatedSitesLayoutSettingsIndexRoute,
  }

const AppAuthenticatedSitesLayoutSettingsRouteWithChildren =
  AppAuthenticatedSitesLayoutSettingsRoute._addFileChildren(
    AppAuthenticatedSitesLayoutSettingsRouteChildren,
  )

interface AppAuthenticatedSitesLayoutRouteChildren {
  AppAuthenticatedSitesLayoutSettingsRoute: typeof AppAuthenticatedSitesLayoutSettingsRouteWithChildren
  AppAuthenticatedSitesLayoutIndexRoute: typeof AppAuthenticatedSitesLayoutIndexRoute
}

const AppAuthenticatedSitesLayoutRouteChildren: AppAuthenticatedSitesLayoutRouteChildren =
  {
    AppAuthenticatedSitesLayoutSettingsRoute:
      AppAuthenticatedSitesLayoutSettingsRouteWithChildren,
    AppAuthenticatedSitesLayoutIndexRoute:
      AppAuthenticatedSitesLayoutIndexRoute,
  }

const AppAuthenticatedSitesLayoutRouteWithChildren =
  AppAuthenticatedSitesLayoutRoute._addFileChildren(
    AppAuthenticatedSitesLayoutRouteChildren,
  )

interface AppAuthenticatedSitesRouteChildren {
  AppAuthenticatedSitesLayoutRoute: typeof AppAuthenticatedSitesLayoutRouteWithChildren
  AppAuthenticatedSitesSiteIdIndexRoute: typeof AppAuthenticatedSitesSiteIdIndexRoute
}

const AppAuthenticatedSitesRouteChildren: AppAuthenticatedSitesRouteChildren = {
  AppAuthenticatedSitesLayoutRoute:
    AppAuthenticatedSitesLayoutRouteWithChildren,
  AppAuthenticatedSitesSiteIdIndexRoute: AppAuthenticatedSitesSiteIdIndexRoute,
}

const AppAuthenticatedSitesRouteWithChildren =
  AppAuthenticatedSitesRoute._addFileChildren(
    AppAuthenticatedSitesRouteChildren,
  )

interface AppAuthenticatedRouteChildren {
  AppAuthenticatedOnboardingRoute: typeof AppAuthenticatedOnboardingRouteWithChildren
  AppAuthenticatedSitesRoute: typeof AppAuthenticatedSitesRouteWithChildren
}

const AppAuthenticatedRouteChildren: AppAuthenticatedRouteChildren = {
  AppAuthenticatedOnboardingRoute: AppAuthenticatedOnboardingRouteWithChildren,
  AppAuthenticatedSitesRoute: AppAuthenticatedSitesRouteWithChildren,
}

const AppAuthenticatedRouteWithChildren =
  AppAuthenticatedRoute._addFileChildren(AppAuthenticatedRouteChildren)

interface AppRouteChildren {
  AppAuthenticatedRoute: typeof AppAuthenticatedRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthenticatedRoute: AppAuthenticatedRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppAuthenticatedRouteWithChildren
  '/onboarding': typeof AppAuthenticatedOnboardingLayoutRouteWithChildren
  '/sites': typeof AppAuthenticatedSitesLayoutRouteWithChildren
  '/onboarding/username': typeof AppAuthenticatedOnboardingLayoutUsernameRoute
  '/sites/settings': typeof AppAuthenticatedSitesLayoutSettingsRouteWithChildren
  '/sites/$siteId': typeof AppAuthenticatedSitesSiteIdIndexRoute
  '/sites/': typeof AppAuthenticatedSitesLayoutIndexRoute
  '/sites/settings/': typeof AppAuthenticatedSitesLayoutSettingsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppAuthenticatedRouteWithChildren
  '/onboarding': typeof AppAuthenticatedOnboardingLayoutRouteWithChildren
  '/sites': typeof AppAuthenticatedSitesLayoutIndexRoute
  '/onboarding/username': typeof AppAuthenticatedOnboardingLayoutUsernameRoute
  '/sites/$siteId': typeof AppAuthenticatedSitesSiteIdIndexRoute
  '/sites/settings': typeof AppAuthenticatedSitesLayoutSettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_authenticated': typeof AppAuthenticatedRouteWithChildren
  '/_app/_authenticated/onboarding': typeof AppAuthenticatedOnboardingRouteWithChildren
  '/_app/_authenticated/onboarding/_layout': typeof AppAuthenticatedOnboardingLayoutRouteWithChildren
  '/_app/_authenticated/sites': typeof AppAuthenticatedSitesRouteWithChildren
  '/_app/_authenticated/sites/_layout': typeof AppAuthenticatedSitesLayoutRouteWithChildren
  '/_app/_authenticated/onboarding/_layout/username': typeof AppAuthenticatedOnboardingLayoutUsernameRoute
  '/_app/_authenticated/sites/_layout/settings': typeof AppAuthenticatedSitesLayoutSettingsRouteWithChildren
  '/_app/_authenticated/sites/$siteId/': typeof AppAuthenticatedSitesSiteIdIndexRoute
  '/_app/_authenticated/sites/_layout/': typeof AppAuthenticatedSitesLayoutIndexRoute
  '/_app/_authenticated/sites/_layout/settings/': typeof AppAuthenticatedSitesLayoutSettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/onboarding'
    | '/sites'
    | '/onboarding/username'
    | '/sites/settings'
    | '/sites/$siteId'
    | '/sites/'
    | '/sites/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/onboarding'
    | '/sites'
    | '/onboarding/username'
    | '/sites/$siteId'
    | '/sites/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_authenticated'
    | '/_app/_authenticated/onboarding'
    | '/_app/_authenticated/onboarding/_layout'
    | '/_app/_authenticated/sites'
    | '/_app/_authenticated/sites/_layout'
    | '/_app/_authenticated/onboarding/_layout/username'
    | '/_app/_authenticated/sites/_layout/settings'
    | '/_app/_authenticated/sites/$siteId/'
    | '/_app/_authenticated/sites/_layout/'
    | '/_app/_authenticated/sites/_layout/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_authenticated"
      ]
    },
    "/_app/_authenticated": {
      "filePath": "_app/_authenticated.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_authenticated/onboarding",
        "/_app/_authenticated/sites"
      ]
    },
    "/_app/_authenticated/onboarding": {
      "filePath": "_app/_authenticated/onboarding",
      "parent": "/_app/_authenticated",
      "children": [
        "/_app/_authenticated/onboarding/_layout"
      ]
    },
    "/_app/_authenticated/onboarding/_layout": {
      "filePath": "_app/_authenticated/onboarding/_layout.tsx",
      "parent": "/_app/_authenticated/onboarding",
      "children": [
        "/_app/_authenticated/onboarding/_layout/username"
      ]
    },
    "/_app/_authenticated/sites": {
      "filePath": "_app/_authenticated/sites",
      "parent": "/_app/_authenticated",
      "children": [
        "/_app/_authenticated/sites/_layout",
        "/_app/_authenticated/sites/$siteId/"
      ]
    },
    "/_app/_authenticated/sites/_layout": {
      "filePath": "_app/_authenticated/sites/_layout.tsx",
      "parent": "/_app/_authenticated/sites",
      "children": [
        "/_app/_authenticated/sites/_layout/settings",
        "/_app/_authenticated/sites/_layout/"
      ]
    },
    "/_app/_authenticated/onboarding/_layout/username": {
      "filePath": "_app/_authenticated/onboarding/_layout.username.tsx",
      "parent": "/_app/_authenticated/onboarding/_layout"
    },
    "/_app/_authenticated/sites/_layout/settings": {
      "filePath": "_app/_authenticated/sites/_layout.settings.tsx",
      "parent": "/_app/_authenticated/sites/_layout",
      "children": [
        "/_app/_authenticated/sites/_layout/settings/"
      ]
    },
    "/_app/_authenticated/sites/$siteId/": {
      "filePath": "_app/_authenticated/sites/$siteId/index.tsx",
      "parent": "/_app/_authenticated/sites"
    },
    "/_app/_authenticated/sites/_layout/": {
      "filePath": "_app/_authenticated/sites/_layout.index.tsx",
      "parent": "/_app/_authenticated/sites/_layout"
    },
    "/_app/_authenticated/sites/_layout/settings/": {
      "filePath": "_app/_authenticated/sites/_layout.settings.index.tsx",
      "parent": "/_app/_authenticated/sites/_layout/settings"
    }
  }
}
ROUTE_MANIFEST_END */
